# Generated by Django 4.0 on 2022-05-02 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('timer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_log',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='user_log',
            name='pause',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='user_log',
            name='start_time',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='TimeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occur_time', models.DateTimeField()),
                ('tag_name', models.IntegerField()),
                ('user_log', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.usertype')),
            ],
        ),
    ]
