# Generated by Django 4.0 on 2022-05-03 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
        ('accounts', '0001_initial'),
        ('timer', '0002_alter_user_log_end_time_alter_user_log_pause_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('abnomal_time', models.DateTimeField(null=True)),
                ('tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tag.tag')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.user')),
            ],
        ),
        migrations.RenameField(
            model_name='timelog',
            old_name='tag_name',
            new_name='event_type',
        ),
        migrations.RenameField(
            model_name='timelog',
            old_name='occur_time',
            new_name='time',
        ),
        migrations.DeleteModel(
            name='User_log',
        ),
        migrations.AlterField(
            model_name='timelog',
            name='user_log',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='timer.userlog'),
        ),
    ]
