# Generated by Django 4.0 on 2022-05-05 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0003_userlog_rename_tag_name_timelog_event_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
