# Generated by Django 4.0 on 2022-05-06 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BulletinFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('upload_time', models.DateTimeField(null=True)),
                ('content', models.TextField(max_length=255, null=True)),
                ('img_path', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
